server:
  port: 8080
  servlet:
    context-path: /Test


spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.0.108:1521/orcl
    username: wanghong_test
    password: root